name: stemeye_pdf_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

  #--------------- PACKAGES ------------------#

dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  dio: ^5.7.0
  permission_handler: ^11.3.1
  file_saver: ^0.2.14
  file_picker: ^8.1.2
  pdf: ^3.11.1  
  archive: ^3.6.1
  path_provider: ^2.1.4
  flutter_colorpicker: ^1.1.0
  syncfusion_flutter_pdfviewer: ^27.1.51
  liquid_progress_indicator_v2: ^0.5.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  open_file: ^3.5.9
  shared_preferences: ^2.3.2
  share_plus: ^10.1.0
  webview_flutter: ^4.0.4 
  
  
  
  #Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  
  
  #State Management
  get: ^4.6.6

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
    - assets/conversion_icons/
    - assets/project_import/
    - assets/convert_file/

  
  #--------------- LOCAL FONTS ------------------#


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
